version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: kyc-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kyc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: kycuser
      RABBITMQ_DEFAULT_PASS: kycpass123
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build: ./server
    container_name: kyc-server
    depends_on:
      - mongo
      - rabbitmq
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/kyc
      JWT_SECRET: change_me
      RABBITMQ_URL: amqp://kycuser:kycpass123@rabbitmq:5672
      HUGGING_FACE_API_KEY: ${HUGGING_FACE_API_KEY:-}
    ports:
      - "5000:5000"

  client:
    build: ./client
    container_name: kyc-client
    depends_on:
      - server
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"

volumes:
  mongo-data:
